dicas = [
"Conjunto de atividades que têm por finalidade a descoberta de novos conhecimentos no domínio científico, literário, artístico etc.",
"Pode ser diferenciada em primária, secundária e terciária",
"Tem a intenção de esclarecer aquilo que o pesquisador pretende desenvolver, desde os caminhos teóricos até os resultados a serem alcançados.",
"São as características práticas de uma pesquisa.",
"Busca apresentar conhecimento novo a partir de observações e teorias construídas para exlicá-las",
"Busca obter informações apenas em trabalhos já publicados",
"Revisão sistemática de revisões sistemáticas",
"É aquela em que o autor não tem uma hipótese ou objetivo em mente",
"Busca-se obter dados mais consistentes sobre determinada realidade, mas não há ainda interferência do pesquisador ou a tentativa de obter teorias que expliquem os fenômenos.",
"É a mais completa pois, além de analisar os dados observados, abbisca suas causas e explicações.",
"É a pesquisa relacionada com a determinação de como as coisas poderiam ser",
"Implica o estudo de artigos, teses, livros e outras publicações",
"Análise de dados e documentos que ainda não foram sistematizados ou publicados",
"Manipulação de um aspecto da realidade pelo pesquisador",
"Aplicação de questionários a grupos de pessoas",
"Ocorre quando um pesquisador mergulha em um grupo social para observar seus comportamentos",
"É o conhecimento que explica os fenômenos obedecendo a leis que foram verificadas por métodos experimentais",
"É um produto da ciência e da engenharia que envolve um conjunto de instrumentos, métodos e técnicas que visam a resolução de problemas.",
"pode ser definida como a busca de solução para um problema a partir de entradas (inputs), de forma a obter resultados (outputs) depois de processada a informação através de um algoritmo.",
"É a suposição de algo que pode (ou não) ser verosímil, que seja possível de ser verificado, a partir da qual se extrai uma conclusão.",
"É um fato que se apoia somente em experiências vividas, na observação de coisas, e não em teorias e métodos científicos.",
"Que respeita leis em vigor ou se adapta às normas estabelecidas.",
"É uma explicação de um aspecto do mundo natural e do universo que foi repetidamente testado e verificado de acordo com o método científico, usando protocolos de observação, medida e avaliação dos resultados. ",
"Sobrenome do autor que a professora ama! S2",
"Nome do autor que a professora ama! S2",
"É a escolha de procedimentos sistemáticos para a descrição e a explicação de fenômenos.",
"Agente por trás do ato da descoberta",
"Trata-se de uma imagem ou representação mental de um objeto.",
"É uma sequência de raciocínios, instruções ou operações para alcançar um objetivo, sendo necessário que os passos sejam finitos e operados sistematicamente.",
"É um versão inicial, reduzida proporcionalmente, da solução de sistema ou de parte de uma solução de sistema construída em um curto período de tempo e aprimorada em várias iterações para testar e avaliar a eficácia do design global utilizado para resolver um problema específico.",
"É um conjunto de atividades estruturadas e medidas destinadas a resultar em um produto especificado"]